backend:
  name: git-gateway
  repo: amansalmani073/latest-article
  branch: main
  site_domain: enchanting-manatee-ff58a1.netlify.app

media_folder: "images/uploads"
public_folder: "/latest-article/images/uploads"

collections:
  - name: "blog"
    label: "Blog Post"
    folder: "articles"
    create: true
    slug: "{{slug}}/index"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
